version: '3.8'

services:
  web:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/restaurant_db
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn restaurant_project.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=restaurant_db
    ports:
      - "5433:5432"
    restart: always

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  celery:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/restaurant_db
    command: celery -A restaurant_project worker --loglevel=info

  celery-beat:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/restaurant_db
    command: celery -A restaurant_project beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler

  nginx:
    image: nginx:1.23
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume: 