# Generated by Django 5.2 on 2025-06-04 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('domain', models.CharField(max_length=200, validators=[django.core.validators.URLValidator()], verbose_name='Домен')),
                ('station_id', models.CharField(max_length=50, verbose_name='ID станции')),
                ('table_number', models.PositiveIntegerField(verbose_name='Номер стола')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'QR код',
                'verbose_name_plural': 'QR коды',
                'ordering': ['-created_at'],
            },
        ),
    ]
