# Generated by Django 5.2 on 2025-04-18 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название станции')),
                ('rkeeper_code', models.CharField(max_length=10, unique=True, verbose_name='Код станции в R-Keeper')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Станция',
                'verbose_name_plural': 'Станции',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='rkeeper_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID в R-Keeper'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступно'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='rkeeper_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID в R-Keeper'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='menu_photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='category',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.station', verbose_name='Станция'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.station', verbose_name='Станция'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'station')},
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('rkeeper_id', 'station')},
        ),
    ]
