# Generated by Django 5.2 on 2025-04-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_station_category_rkeeper_id_menuitem_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='rkeeper_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ID станции в R-Keeper'),
        ),
    ]
