# Generated by Django 5.2 on 2025-04-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_station_rkeeper_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='r_keeper_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер станции в R-Keeper'),
        ),
    ]
