# Generated by Django 5.2 on 2025-05-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_menuitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Состав (казахский)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_kk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название блюда (казахский)'),
        ),
    ]
