# Generated by Django 5.2 on 2025-05-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_menuitem_description_kk_menuitem_name_kk'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
