# Generated by Django 5.2 on 2025-05-19 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_menuitem_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='comment',
        ),
    ]
