# Generated by Django 5.2 on 2025-07-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_remove_menuitem_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='stop_list',
            field=models.BooleanField(default=False, verbose_name='Выключено в меню вручную'),
        ),
    ]
