# Generated by Django 5.2 on 2025-04-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status_alter_order_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='station_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID станции в R-Keeper'),
        ),
    ]
