# Generated by Django 5.2 on 2025-06-04 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_comment_orderitem_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код официанта')),
                ('name', models.CharField(max_length=100, verbose_name='Имя официанта')),
                ('guid', models.CharField(blank=True, max_length=100, null=True, verbose_name='GUID в R-Keeper')),
                ('table_number', models.IntegerField(blank=True, null=True, verbose_name='Номер стола')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Официант',
                'verbose_name_plural': 'Официанты',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='waiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.waiter', verbose_name='Официант'),
        ),
    ]
