# Generated by Django 5.2 on 2025-06-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_table_number_remove_waiter_table_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название стола'),
        ),
    ]
